### ISSUE TITLE
WebSocket connection failed - content-security-policy

### ISSUE THREAD

**Issue by guilhebl** [playframework/play-scala-chatroom-example#28]
Running with latest version 2.6.x.
Browser is refusing to connect to websocket on ws://localhost:9000

Browsers:

Chrome : Version 59.0.3071.109
Firefox: 47.0

ERROR in console:
> Content Security Policy: The page's settings blocked the loading of a resource at ws://localhost:9000/myapp ("default-src http://localhost:9000").

I Provided a fix and some other enhancements based on pull request:
https://github.com/playframework/play-scala-chatroom-example/pull/27

**Comment by wsargent** [comment]
Merged
